name = "code-review-agent"
main = "dist/index.js"
compatibility_date = "2024-03-15"

[build]
command = "npm run build"

[env.production]
workers_dev = true

# 配置绑定 - 在 Cloudflare Dashboard 中设置这些环境变量
# [vars]
# OPENAI_API_KEY = ""