name = "code-review-agent"
main = "src/mastra/index.ts"
compatibility_date = "2024-03-15"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[env.production]
workers_dev = true
